//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ap_user()
        {
            this.parked_car = new HashSet<parked_car>();
            this.parkedcar_viewlog = new HashSet<parkedcar_viewlog>();
            this.payments = new HashSet<payment>();
            this.user_daycount = new HashSet<user_daycount>();
        }
    
        public System.Guid id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string cnic { get; set; }
        public string contact_no { get; set; }
        public string phone_no { get; set; }
        public string address { get; set; }
        public Nullable<bool> is_block { get; set; }
        public string terminal { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string username { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ap_role ap_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parked_car> parked_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parkedcar_viewlog> parkedcar_viewlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_daycount> user_daycount { get; set; }
    }
}
