//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dur_amount
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> veh_type_id { get; set; }
        public string duration_time { get; set; }
        public Nullable<double> amount_to_charge { get; set; }
        public Nullable<bool> is_challaned { get; set; }
    
        public virtual veh_type veh_type { get; set; }
    }
}
