//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class duration_charges
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> duration_id { get; set; }
        public Nullable<double> amount { get; set; }
        public string description { get; set; }
    
        public virtual duration duration { get; set; }
    }
}
