//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class duration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public duration()
        {
            this.duration_charges = new HashSet<duration_charges>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<int> duration_value { get; set; }
        public Nullable<bool> is_hourly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<duration_charges> duration_charges { get; set; }
    }
}
