//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_reg
    {
        public System.Guid id { get; set; }
        public string vehicle_no { get; set; }
        public Nullable<System.DateTime> date_registered { get; set; }
        public Nullable<double> amount { get; set; }
        public string month_name { get; set; }
        public string cnic { get; set; }
        public string contact_no { get; set; }
        public string ownername { get; set; }
    }
}
