//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class parked_car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parked_car()
        {
            this.parkedcar_viewlog = new HashSet<parkedcar_viewlog>();
        }
    
        public System.Guid id { get; set; }
        public string car_no { get; set; }
        public Nullable<System.Guid> veh_type { get; set; }
        public string assigned_no { get; set; }
        public Nullable<System.DateTime> parkin_time { get; set; }
        public Nullable<System.DateTime> parkout_time { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<double> charged_amount { get; set; }
        public Nullable<double> paid_amount { get; set; }
        public string parked_duration { get; set; }
        public long recript_no { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<bool> is_challaned { get; set; }
        public Nullable<bool> is_monthly { get; set; }
        public Nullable<System.Guid> out_by { get; set; }
        public Nullable<bool> is_nightly { get; set; }
        public Nullable<bool> is_updateby_admin { get; set; }
        public string checkinimage { get; set; }
        public string checkoutimage { get; set; }
    
        public virtual ap_user ap_user { get; set; }
        public virtual veh_type veh_type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parkedcar_viewlog> parkedcar_viewlog { get; set; }
    }
}
