//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_v2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_daycount
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> act_date { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<int> total_cars { get; set; }
    
        public virtual ap_user ap_user { get; set; }
    }
}
